export const PRE_A1_VOCABULARY = `
animal, baby, back, bag, ball, banana, band, bank, bath, bathroom, bed, bedroom, bird, birthday,
book, boy, bread, brother, bus, car, cat, chair, chicken, city, class, clock, clothes, coat, coffee,
day, dog, door, dress, ear, egg, elephant, eye, face, family, father, fish, floor, flower, food, foot,
friend, garden, girl, hand, hat, home, horse, house, juice, key, kitchen, lamp, letter, line, lion,
man, milk, money, mother, mouse, mouth, night, nose, orange, park, pen, pencil, photo, place, rabbit,
rain, restaurant, river, school, sea, shoe, sister, star, street, sun, table, teacher, telephone, time, tree, water, window, woman, year,
add, ask, be, become, begin, believe, break, bring, build, buy, call, can, clean, climb, close, come,
cook, cut, dance, do, drink, eat, find, fly, follow, get, give, go, have, help, hear, hold, jump,
keep, know, laugh, learn, leave, like, listen, live, look, lose, love, make, move, open, play, put,
read, run, say, see, sell, send, sing, sit, sleep, speak, stand, start, stop, study, swim, take, talk,
teach, tell, think, travel, try, turn, understand, use, wait, walk, want, watch, work, write,
afraid, angry, big, black, blue, cold, dangerous, dark, different, easy, expensive, fast, funny,
good, happy, hard, hot, hungry, important, interesting, large, late, little, long, loud, nice, old, open, perfect,
pink, popular, pretty, quick, quiet, red, small, soft, strong, tall, tired, true, warm, weak, white, young,
about, after, against, at, before, between, by, down, for, from, in, near, of, on, over, to, under, with,
one, two, three, four, five, six, seven, eight, nine, ten,
eleven, twelve, thirteen, fourteen, fifteen, sixteen, seventeen, eighteen, nineteen, twenty,
morning, afternoon, evening, night, today, tomorrow, yesterday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday
`.replace(/\n/g, ' ').replace(/\s+/g, ' ');

export const A1_VOCABULARY = `
adult, advice, afternoon, airport, animal, apple, April, arm, art, artist, autumn,
baby, back, bag, ball, banana, bank, bathroom, bed, bedroom, bee, bird, birthday, boat, body, book,
boy, bread, brother, bus, cake, camera, car, carpet, cat, chair, cheese, child, chocolate, city, classroom, clothes,
club, coast, coat, coffee, college, colour, company, concert, cook, country, cousin, cow, cup, day, desk, doctor, door,
dress, drink, driver, ear, earth, egg, elephant, end, eye, face, family, father, finger, fish, floor, flower, food,
foot, football, friend, garden, girl, glass, grandfather, grandmother, grass, guitar, hair, hand, hat, head, health, heart,
holiday, home, horse, hotel, hour, house, ice, ice cream, idea, island, January, jeans, job, juice, key, kitchen, lake, language,
laugh, leaf, leg, letter, library, life, light, line, lion, list, liver, living room, love, lunch, magazine, man, market, meal,
milk, money, month, morning, mother, mountain, mouse, mouth, music, name, neck, neighbour, night, nose, November, number, ocean, office,
open, orange, order, page, paint, paper, party, pen, pencil, photo, picture, pig, place, plane, plant, plate, play, police, pool,
pot, rain, restaurant, river, road, room, school, sea, seat, shop, sister, sky, sleep, snow, soap, sofa, son, song, soup, sport, star,
station, street, student, sun, Sunday, table, taxi, tea, teacher, telephone, television, test, theatre, Thursday, ticket, time, town, train, tree,
Tuesday, umbrella, uncle, university, vegetable, village, wall, watch, water, way, weather, Wednesday, week, weekend, window, winter, woman,
year, yellow, young,
add, agree, arrive, ask, be, become, begin, believe, break, bring, build, buy, call, can, carry,
catch, change, clean, climb, close, come, cook, cost, could, count, dance, do, draw, drink, drive, eat, explain,
fall, feel, find, fly, forget, get, give, go, grow, guess, happen, have, hear, help, hope, jump, keep, know, learn,
leave, like, listen, live, look, lose, love, make, move, need, open, paint, play, put, read, ride, ring, run, say,
see, sell, send, sing, sit, sleep, speak, spend, stand, start, stop, study, swim, take, talk, teach, tell, think, travel,
try, turn, understand, use, wait, walk, want, watch, win, work, write,
afraid, angry, bad, beautiful, big, blonde, blue, busy, cheap, clean, clear, cold, comfortable, cool, dangerous,
dark, different, difficult, dirty, dry, early, easy, expensive, fast, fat, few, good, green, happy, hard, healthy,
high, hot, hungry, important, interesting, large, late, light, little, long, loud, lovely, low, new, nice, old,
open, pink, poor, popular, pretty, quick, quiet, red, rich, sad, safe, short, slow, small, soft, special, strong, tall,
thin, tired, true, warm, weak, white, wide, young,
about, after, all, also, always, and, any, around, at, back, before, behind, between, both, but, by,
can, come, for, from, get, go, have, he, her, here, him, his, how, I, if, in, into, is, it, its,
like, me, my, no, not, of, on, one, or, out, over, she, some, take, that, the, their, them, then,
there, these, they, this, to, up, us, was, we, what, when, where, which, who, will, with, you, your,
one, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve, thirteen, fourteen, fifteen,
morning, afternoon, evening, night, today, tomorrow, yesterday,
Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday
`.replace(/\n/g, ' ').replace(/\s+/g, ' ');
